services:
  - type: web
    name: skin-disease-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
